_wandb:
    value:
        cli_version: 0.25.1
        e:
            n3geowau3nvmvn2mhezkruiypolgp53e:
                codePath: compat_fit.py
                codePathLocal: compat_fit.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "982820896768"
                        used: "842158620672"
                email: sayak.dutta@iitgn.ac.in
                executable: /home/shashikant/anaconda3/envs/spc/bin/python
                gpu: NVIDIA RTX A5000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8192
                      memoryTotal: "25757220864"
                      name: NVIDIA RTX A5000
                      uuid: GPU-aad05882-d4c8-7a50-55af-0a3f504eae5c
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-4b547941-9a44-374c-02b5-3d83dd27eddc
                host: Cooler-System-Rog
                memory:
                    total: "67114516480"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /mnt/zone/A/QuantaBurst/compat_fit.py
                python: CPython 3.10.20
                root: /mnt/zone/A/QuantaBurst
                startedAt: "2026-04-18T00:39:37.654019Z"
                writerId: n3geowau3nvmvn2mhezkruiypolgp53e
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
                - 105
            "2":
                - 1
                - 41
                - 105
            "3":
                - 13
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 1
cosine_t_max:
    value: 200
crop_size:
    value: 384
ema_decay:
    value: 0.999
eta_min:
    value: 1e-06
grad_clip:
    value: 1
lr:
    value: 0.0002
num_epochs:
    value: 200
psnr_gate:
    value: 34
ramp_epochs:
    value: 15
w_charb:
    value: 0.5
w_edge:
    value: 0.1
w_fft:
    value: 0.05
w_msssim:
    value: 0.3
w_vgg:
    value: 0.1
